# Generated by Django 2.1.5 on 2019-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chessboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(default=0)),
                ('user_id1', models.IntegerField(default=0)),
                ('user_id2', models.IntegerField(default=0)),
                ('username1', models.CharField(default='Vacant', max_length=20)),
                ('username2', models.CharField(default='Vacant', max_length=20)),
                ('isFirstinaRow', models.BooleanField()),
                ('isLastinaRow', models.BooleanField()),
                ('isReady1', models.BooleanField(default=False)),
                ('isReady2', models.BooleanField(default=False)),
                ('last_refresh_time', models.DateTimeField()),
                ('current_user', models.CharField(default='Vacant', max_length=20)),
                ('current_chess_id', models.IntegerField(default=0)),
                ('endofgame', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chesspiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_index', models.IntegerField(default=0)),
                ('sequence_index', models.IntegerField(default=0)),
                ('row_index', models.IntegerField()),
                ('column_index', models.IntegerField()),
                ('status', models.IntegerField()),
                ('id_on_board', models.IntegerField(default=300)),
                ('color', models.CharField(default='#FFE4B5', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gamerecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_record', models.CharField(max_length=800)),
                ('ending_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('picture', models.FileField(blank=True, upload_to='static/images/')),
                ('content_type', models.CharField(max_length=50)),
                ('game_sum', models.IntegerField()),
                ('win_sum', models.IntegerField()),
                ('game_records', models.ManyToManyField(blank=True, to='OnlineFiveinaRow.Gamerecord')),
            ],
        ),
    ]
